// this file is generated by 'stencil-to-storybook.js' aka pre-storybook npm task

import markdown from './readme.md';
import { h } from '../../utils/storybook';

export default {
  ...{
    component: 'w-image',
    args: {
      src: 'https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg',
      lazy: false,
      fit: '',
      placeholder: '',
      errorText: '',
    },
    argTypes: {
      src: {
        description: 'Prop src 图片链接1',
      },
      lazy: {
        description: 'Prop lazy 是否懒加载',
      },
      fit: {
        description: 'Prop fit 图片填充格式',
      },
      placeholder: {
        description: 'Prop placeholder 加载文案',
      },
      errorText: {
        description: 'Prop 错误文案',
      },
    },
    customEvents: [],
    slots: {},
  },
  markdown,
  tpl: ({}) => h`
    <div class="image-container">
      none
      <w-image fit="none" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c259411.jpeg"></w-image>
      contain
      <w-image fit="contain" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg"></w-image>
      cover
      <w-image fit="cover" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg"></w-image>
      fill
      <w-image fit="fill" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg"></w-image>
      scale-down
      <w-image fit="scale-down" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg"></w-image>
    </div>
    `,
};
