/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface MyComponent {
    /**
     * The first name
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     */
    middle: string;
  }
  interface WIcon {}
  interface WIconAbsolute_stroked {}
  interface WIconAlarm {}
  interface WImage {
    /**
     * Prop 错误文案
     */
    errorText: string;
    /**
     * Prop fit 图片填充格式
     */
    fit: 'none' | 'contain' | 'cover' | 'fill' | 'scale-down';
    /**
     * Prop lazy 是否懒加载
     */
    lazy: boolean;
    /**
     * Prop placeholder 加载文案
     */
    placeholder: string;
    /**
     * Prop src 图片链接
     */
    src: string;
  }
}
declare global {
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLWIconElement extends Components.WIcon, HTMLStencilElement {}
  var HTMLWIconElement: {
    prototype: HTMLWIconElement;
    new (): HTMLWIconElement;
  };
  interface HTMLWIconAbsolute_strokedElement extends Components.WIconAbsolute_stroked, HTMLStencilElement {}
  var HTMLWIconAbsolute_strokedElement: {
    prototype: HTMLWIconAbsolute_strokedElement;
    new (): HTMLWIconAbsolute_strokedElement;
  };
  interface HTMLWIconAlarmElement extends Components.WIconAlarm, HTMLStencilElement {}
  var HTMLWIconAlarmElement: {
    prototype: HTMLWIconAlarmElement;
    new (): HTMLWIconAlarmElement;
  };
  interface HTMLWImageElement extends Components.WImage, HTMLStencilElement {}
  var HTMLWImageElement: {
    prototype: HTMLWImageElement;
    new (): HTMLWImageElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'w-icon': HTMLWIconElement;
    'w-icon-absolute_stroked': HTMLWIconAbsolute_strokedElement;
    'w-icon-alarm': HTMLWIconAlarmElement;
    'w-image': HTMLWImageElement;
  }
}
declare namespace LocalJSX {
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }
  interface WIcon {}
  interface WIconAbsolute_stroked {}
  interface WIconAlarm {}
  interface WImage {
    /**
     * Prop 错误文案
     */
    errorText?: string;
    /**
     * Prop fit 图片填充格式
     */
    fit?: 'none' | 'contain' | 'cover' | 'fill' | 'scale-down';
    /**
     * Prop lazy 是否懒加载
     */
    lazy?: boolean;
    /**
     * Prop placeholder 加载文案
     */
    placeholder?: string;
    /**
     * Prop src 图片链接
     */
    src?: string;
  }
  interface IntrinsicElements {
    'my-component': MyComponent;
    'w-icon': WIcon;
    'w-icon-absolute_stroked': WIconAbsolute_stroked;
    'w-icon-alarm': WIconAlarm;
    'w-image': WImage;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'w-icon': LocalJSX.WIcon & JSXBase.HTMLAttributes<HTMLWIconElement>;
      'w-icon-absolute_stroked': LocalJSX.WIconAbsolute_stroked & JSXBase.HTMLAttributes<HTMLWIconAbsolute_strokedElement>;
      'w-icon-alarm': LocalJSX.WIconAlarm & JSXBase.HTMLAttributes<HTMLWIconAlarmElement>;
      'w-image': LocalJSX.WImage & JSXBase.HTMLAttributes<HTMLWImageElement>;
    }
  }
}
