// this file is generated by 'stencil-to-storybook.js' aka pre-storybook npm task

import markdown from './readme.md';
import { a, h } from '../../utils/storybook';

export default {
  ...{
    component: 'Components/w-icon',
    args: {},
    argTypes: {},
    customEvents: [],
    slots: {},
  },
  markdown,
  tpl: ({ id }) => h`
    <w-icon
      id="${a(id)}"
    ></w-icon>`,
};
