// this file is generated by 'stencil-to-storybook.js' aka pre-storybook npm task

import markdown from './readme.md';
import { a, h } from '../../utils/storybook';

export default {
  ...{
    component: 'my-component',
    args: {
      first: '',
      middle: '',
      last: '',
    },
    argTypes: {
      first: {
        description: 'First Prop',
      },
      middle: {
        description: 'Middle Prop',
      },
      last: {
        description: 'Last Prop',
      },
    },
    customEvents: [],
    slots: {},
  },
  markdown,
  tpl: ({ id, first, middle, last }) => h`
    <my-component
      id="${a(id)}"
			first="${a(first)}"
			middle="${a(middle)}"
			last="${a(last)}"
    ></my-component>`,
};
